spring.datasource.url=jdbc:mysql://localhost:3306/NerdWarehouse
spring.datasource.username=root
spring.datasource.password=admin94
spring.jpa.hibernate.ddl-auto=update
spring.datasource.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#mette il server in ascolto sulla porta 8010
server.port=8010
#Permette l'override dei Bean. Nel nostro progetto è RICHIESTO, altrimenti non parte
spring.main.allow-bean-definition-overriding=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=k27460224@gmail.com
spring.mail.password=hkrv kvvu dfvb nbrv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
//progettinoingsw1
